version: '3.9'
services:
  p2p:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: enwaiax/peer2profit:test
    restart: unless-stopped
    environment:
      - email=chasing66@live.com
      - use_proxy=true
    volumes:
      - ./proxychains4.conf:/root/proxychains4.conf
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging: 
      driver: "local"
      options:
        max-size: "1m"
